# Generated by Django 5.2.10 on 2026-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=100, verbose_name='信誉分'),
        ),
    ]
