# Generated by Django 5.2.10 on 2026-01-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '商品评论', 'verbose_name_plural': '商品评论'},
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='回复对象'),
        ),
    ]
