# Generated by Django 5.2.10 on 2026-02-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_options_comment_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='评价图片'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
